/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Correo;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class Visualizar extends javax.swing.JFrame implements java.io.Serializable{

    /**
     * Creates new form Visualizar
     */
    Nodo r=null;
    Multilista ml;
    String arr3[]= new String[3];
    String path="multilista.obj";
    FileInputStream fi;
    ObjectInputStream oi;
    String correo;
    String nombre;
    int edad;
    static Pila pB; //pila bandeja de entrada
    static Pila pE; //pila enviados
    static Pila pL; //pila eliminados
    static Pila pS; //pila spam
    static int ventana=1;
    public Visualizar() {
        super("MyMail");
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        PanelRe.setVisible(false);
        PanelE.setVisible(false);
        DestinoR.setText(correo);
        Origen2.setText(correo);
        Nodo <String> n1 = new Nodo <String> ("14/02/21 | Youtube | JulioProfe ha subido un nuevo...");
        Nodo <String> n2 = new Nodo <String> ("17/02/21 | Facebook | Has recibido una solicitud de...");
        Nodo <String> n3 = new Nodo <String> ("23/02/21 | Instagram | Confirma tu correo electroni...");
        pB.inserta(n1);
        pB.inserta(n2);
        pB.inserta(n3);
        mostrarBandeja();
    }
    public Visualizar(String nombre,String c, int e, Nodo r, Multilista m, Pila pb, Pila pe, Pila pl, Pila ps) {
        super("MyMail");
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        PanelRe.setVisible(false);
        PanelE.setVisible(false);
        this.correo = c;
        DestinoR.setText(correo);
        Origen2.setText(correo);
        
        this.nombre = nombre;
        this.edad =e;
        this.r=r;
        this.ml=m;
        pB = pb;
        pE =pe;
        pL=pl;
        pS=ps;
        mostrarBandeja();
        JOptionPane.showMessageDialog(null, "ATENCIÓN!, INSTRUCCIONES:"
        +"\n*Para eliminar un correo introduzca el número que está al lado izquierdo del correo"
                + "\nque desea eliminar en la casilla que está debajo del boton eliminar, después pulse el botón."
                + "\n*Para mandar a spam haga lo mismo pero en la casilla debejo de spam."
                + "\n*Para buscar un correo introduzca el autor o el receptor en el textField al lado de la lupa,"
                + "\nDespués pulse el botón de la lupa."
                + "NOTA: Es importante que ingrese la fecha en el formato DD/MM/YY para que así funcione correctamente"
                + "\nla busqueda de correos"
                + "\n                  GRACIAS POR LEER!            ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Buscar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        Quien = new javax.swing.JButton();
        MostrarE = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        txtEliminar = new javax.swing.JTextField();
        Espam = new javax.swing.JButton();
        txtSpam = new javax.swing.JTextField();
        salir = new javax.swing.JButton();
        cambiar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        Bandeja = new javax.swing.JButton();
        Enviados = new javax.swing.JButton();
        Eliminados = new javax.swing.JButton();
        Spam = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        vista = new javax.swing.JTextArea();
        PanelRe = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        DestinoR = new javax.swing.JLabel();
        OrigenR = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        MensajeR = new javax.swing.JTextArea();
        Recibir = new javax.swing.JButton();
        CancelarR = new javax.swing.JButton();
        diar = new javax.swing.JComboBox<>();
        mesr = new javax.swing.JComboBox<>();
        yearr = new javax.swing.JComboBox<>();
        PanelE = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Origen2 = new javax.swing.JLabel();
        Destino2 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        Mensaje2 = new javax.swing.JTextArea();
        Enviar2 = new javax.swing.JButton();
        Cancelar2 = new javax.swing.JButton();
        diar1 = new javax.swing.JComboBox<>();
        mesr1 = new javax.swing.JComboBox<>();
        yearr1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1364, 724));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mailogo.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MyMail");

        Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar.png"))); // NOI18N
        Buscar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Buscar.setContentAreaFilled(false);
        Buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Buscar.setFocusable(false);
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        txtBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtBuscar.setToolTipText("Buscar");
        txtBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });

        Quien.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        Quien.setForeground(new java.awt.Color(255, 255, 255));
        Quien.setText("Quien soy");
        Quien.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Quien.setContentAreaFilled(false);
        Quien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Quien.setFocusable(false);
        Quien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuienActionPerformed(evt);
            }
        });

        MostrarE.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        MostrarE.setForeground(new java.awt.Color(255, 255, 255));
        MostrarE.setText("Enviar o Recibir");
        MostrarE.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        MostrarE.setContentAreaFilled(false);
        MostrarE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MostrarE.setFocusable(false);
        MostrarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarEActionPerformed(evt);
            }
        });

        Eliminar.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        Eliminar.setForeground(new java.awt.Color(255, 255, 255));
        Eliminar.setText("Eliminar");
        Eliminar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Eliminar.setContentAreaFilled(false);
        Eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Eliminar.setFocusable(false);
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        Espam.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        Espam.setForeground(new java.awt.Color(255, 255, 255));
        Espam.setText("Enviar a spam");
        Espam.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Espam.setContentAreaFilled(false);
        Espam.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Espam.setFocusable(false);
        Espam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EspamActionPerformed(evt);
            }
        });

        salir.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        salir.setForeground(new java.awt.Color(255, 255, 255));
        salir.setText("Salir");
        salir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        salir.setContentAreaFilled(false);
        salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salir.setFocusable(false);
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        cambiar.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        cambiar.setForeground(new java.awt.Color(255, 255, 255));
        cambiar.setText("Cambiar de correo");
        cambiar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cambiar.setContentAreaFilled(false);
        cambiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cambiar.setFocusable(false);
        cambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(Buscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(Quien)
                .addGap(49, 49, 49)
                .addComponent(MostrarE)
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(txtSpam, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(cambiar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(salir))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Eliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Espam)))
                .addContainerGap(395, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Buscar)
                .addGap(19, 19, 19))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Eliminar)
                    .addComponent(Espam))
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Quien)
                    .addComponent(MostrarE)
                    .addComponent(txtEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSpam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salir)
                    .addComponent(cambiar)))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 1634, 90);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 1, 1, 2, new java.awt.Color(0, 0, 0)));

        Bandeja.setBackground(new java.awt.Color(255, 255, 255));
        Bandeja.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Bandeja.setText("Bandeja de entrada");
        Bandeja.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Bandeja.setContentAreaFilled(false);
        Bandeja.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bandeja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BandejaActionPerformed(evt);
            }
        });

        Enviados.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Enviados.setText("Enviados");
        Enviados.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Enviados.setContentAreaFilled(false);
        Enviados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Enviados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnviadosActionPerformed(evt);
            }
        });

        Eliminados.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Eliminados.setText("Eliminados");
        Eliminados.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Eliminados.setContentAreaFilled(false);
        Eliminados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Eliminados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminadosActionPerformed(evt);
            }
        });

        Spam.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Spam.setText("Spam");
        Spam.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Spam.setContentAreaFilled(false);
        Spam.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Spam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Bandeja)
                    .addComponent(Enviados)
                    .addComponent(Eliminados)
                    .addComponent(Spam))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(Bandeja, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(Enviados, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(Eliminados, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(Spam, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 96, 166, 608);

        vista.setEditable(false);
        vista.setColumns(20);
        vista.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        vista.setRows(5);
        jScrollPane1.setViewportView(vista);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(206, 96, 670, 597);

        PanelRe.setBackground(new java.awt.Color(255, 255, 255));
        PanelRe.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel3.setText("Para: ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel4.setText("De: ");

        DestinoR.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        DestinoR.setText("este correo");

        OrigenR.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        OrigenR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrigenRActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel6.setText("Fecha: ");

        MensajeR.setColumns(20);
        MensajeR.setRows(5);
        jScrollPane2.setViewportView(MensajeR);

        Recibir.setText("Recibir");
        Recibir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecibirActionPerformed(evt);
            }
        });

        CancelarR.setText("Cancelar");
        CancelarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarRActionPerformed(evt);
            }
        });

        diar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        mesr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        yearr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2021", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002" }));

        javax.swing.GroupLayout PanelReLayout = new javax.swing.GroupLayout(PanelRe);
        PanelRe.setLayout(PanelReLayout);
        PanelReLayout.setHorizontalGroup(
            PanelReLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelReLayout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(CancelarR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Recibir)
                .addGap(245, 245, 245))
            .addGroup(PanelReLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelReLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelReLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(PanelReLayout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(DestinoR, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE))
                        .addGroup(PanelReLayout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(OrigenR))
                        .addGroup(PanelReLayout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(diar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(mesr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(yearr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelReLayout.setVerticalGroup(
            PanelReLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelReLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelReLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(DestinoR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelReLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(OrigenR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelReLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(diar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mesr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelReLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Recibir)
                    .addComponent(CancelarR))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.add(PanelRe);
        PanelRe.setBounds(882, 96, 480, 295);

        PanelE.setBackground(new java.awt.Color(255, 255, 255));
        PanelE.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        jLabel15.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel15.setText("Para: ");

        jLabel16.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel16.setText("De: ");

        Origen2.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        Origen2.setText("este correo");

        Destino2.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        Destino2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DestinoActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel17.setText("Fecha: ");

        Mensaje2.setColumns(20);
        Mensaje2.setRows(5);
        jScrollPane6.setViewportView(Mensaje2);

        Enviar2.setText("Enviar");
        Enviar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Enviar2ActionPerformed(evt);
            }
        });

        Cancelar2.setText("Cancelar");
        Cancelar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        diar1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        mesr1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        yearr1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2021", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002" }));

        javax.swing.GroupLayout PanelELayout = new javax.swing.GroupLayout(PanelE);
        PanelE.setLayout(PanelELayout);
        PanelELayout.setHorizontalGroup(
            PanelELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelELayout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(Cancelar2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Enviar2)
                .addGap(245, 245, 245))
            .addGroup(PanelELayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelELayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Destino2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelELayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Origen2))
                    .addGroup(PanelELayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(diar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mesr1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yearr1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelELayout.setVerticalGroup(
            PanelELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelELayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(Destino2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(Origen2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(diar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(mesr1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(yearr1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Enviar2)
                    .addComponent(Cancelar2))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.add(PanelE);
        PanelE.setBounds(882, 398, 480, 295);

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel5.setText("2");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(170, 164, 26, 28);

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel7.setText("3");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(170, 210, 26, 28);

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel8.setText("1");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(170, 118, 26, 28);

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel9.setText("4");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(170, 256, 26, 28);

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel10.setText("5");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(170, 310, 26, 28);

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel11.setText("7");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(170, 414, 26, 28);

        jLabel12.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel12.setText("6");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(170, 368, 26, 28);

        jLabel13.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel13.setText("9");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(170, 514, 26, 28);

        jLabel14.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel14.setText("10");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(170, 560, 26, 28);

        jLabel18.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel18.setText("8");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(170, 460, 26, 28);

        jLabel19.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel19.setText("11");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(170, 614, 26, 28);

        jLabel20.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel20.setText("...");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(170, 653, 26, 28);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1366, 704);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void OrigenRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrigenRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OrigenRActionPerformed

    private void MostrarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarEActionPerformed
        PanelRe.setVisible(true);
        PanelE.setVisible(true);
    }//GEN-LAST:event_MostrarEActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        if (txtEliminar.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese el número del mensaje que desea eliminar");
        } else {
            int e = Integer.parseInt(txtEliminar.getText());
            if (ventana==1) {
                Pila aux = new Pila();
                if (pB.getTope()==null) {
                    JOptionPane.showMessageDialog(null, "No hay ningún mensaje en bandeja de entrada");
                } else {
                    if(e==1){
                        pL.inserta(pB.elimina());
                        mostrarBandeja();
                    }else{
                        for (int i = 1; i < e; i++) {
                            aux.inserta(pB.elimina());
                        }
                        if(pB.getTope()==null){
                            JOptionPane.showMessageDialog(null, "No existe un correo con ese número");
                        }else{
                            pL.inserta(pB.elimina());
                        }
                        Nodo de = aux.getTope();
                        while(de!=null){
                            pB.inserta(aux.elimina());
                            de=aux.getTope();
                        }
                        mostrarBandeja();
                    }
                }
            }
            if (ventana==2) {
                Pila aux = new Pila();
                if (pE.getTope()==null) {
                    JOptionPane.showMessageDialog(null, "No hay ningún mensaje en enviados");
                } else {
                    if(e==1){
                        pL.inserta(pE.elimina());
                        mostrarEnviados();
                    }else{
                        for (int i = 1; i < e; i++) {
                            aux.inserta(pE.elimina());
                        }
                        if(pE.getTope()==null){
                            JOptionPane.showMessageDialog(null, "No existe un correo con ese número");
                        }else{
                            pL.inserta(pE.elimina());
                        }
                        Nodo de = aux.getTope();
                        while(de!=null){
                            pE.inserta(aux.elimina());
                            de=aux.getTope();
                        }
                        mostrarEnviados();
                    }
                }
            }
            if (ventana==4) {
                Pila aux = new Pila();
                if (pS.getTope()==null) {
                    JOptionPane.showMessageDialog(null, "No hay ningún mensaje en spam");
                } else {
                    if(e==1){
                        pL.inserta(pS.elimina());
                        mostrarSpam();
                    }else{
                        for (int i = 1; i < e; i++) {
                            aux.inserta(pS.elimina());
                        }
                        if(pS.getTope()==null){
                            JOptionPane.showMessageDialog(null, "No existe un correo con ese número");
                        }else{
                            pL.inserta(pS.elimina());
                        }
                        Nodo de = aux.getTope();
                        while(de!=null){
                            pS.inserta(aux.elimina());
                            de=aux.getTope();
                        }
                        mostrarSpam();
                    }
                }
            }
            if (ventana==3) {
                JOptionPane.showMessageDialog(null, "No se puede eliminar un mensaje que ya fue eliminado");
            }
        }
        txtEliminar.setText("");
        FileOutputStream fo=null;
            try {
                fo = new FileOutputStream(path);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Visualizar.class.getName()).log(Level.SEVERE, null, ex);
            }
            ObjectOutputStream oo=null;
            try {
                oo = new ObjectOutputStream(fo);
            } catch (IOException ex) {
                Logger.getLogger(Visualizar.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                oo.writeObject(r);
            } catch (IOException ex) {
                Logger.getLogger(Visualizar.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                oo.close();
            } catch (IOException ex) {
                Logger.getLogger(Visualizar.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                fo.close();
            } catch (IOException ex) {
                Logger.getLogger(Visualizar.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_EliminarActionPerformed

    private void EspamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EspamActionPerformed
        if (txtSpam.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese el número del mensaje que desea enviar a spam");
        } else {
            int e = Integer.parseInt(txtSpam.getText());
            if (ventana==1) {
                Pila aux = new Pila();
                if (pB.getTope()==null) {
                    JOptionPane.showMessageDialog(null, "No hay ningún mensaje en bandeja de entrada");
                } else {
                    if(e==1){
                        pS.inserta(pB.elimina());
                        mostrarBandeja();
                    }else{
                        for (int i = 1; i < e; i++) {
                            aux.inserta(pB.elimina());
                        }
                        if(pB.getTope()==null){
                            JOptionPane.showMessageDialog(null, "No existe un correo con ese número");
                        }else{
                            pS.inserta(pB.elimina());
                        }
                        Nodo de = aux.getTope();
                        while(de!=null){
                            pB.inserta(aux.elimina());
                            de=aux.getTope();
                        }
                        mostrarBandeja();
                    }
                }
            }
            if (ventana==2) {
                Pila aux = new Pila();
                if (pE.getTope()==null) {
                    JOptionPane.showMessageDialog(null, "No hay ningún mensaje en enviados");
                } else {
                    if(e==1){
                        pS.inserta(pE.elimina());
                        mostrarEnviados();
                    }else{
                        for (int i = 1; i < e; i++) {
                            aux.inserta(pE.elimina());
                        }
                        if(pE.getTope()==null){
                            JOptionPane.showMessageDialog(null, "No existe un correo con ese número");
                        }else{
                            pS.inserta(pE.elimina());
                        }
                        Nodo de = aux.getTope();
                        while(de!=null){
                            pE.inserta(aux.elimina());
                            de=aux.getTope();
                        }
                        mostrarEnviados();
                    }
                }
            }
            if (ventana==3) {
                Pila aux = new Pila();
                if (pL.getTope()==null) {
                    JOptionPane.showMessageDialog(null, "No hay ningún mensaje en eliminados");
                } else {
                    if(e==1){
                        pS.inserta(pL.elimina());
                        mostrarEliminados();
                    }else{
                        for (int i = 1; i < e; i++) {
                            aux.inserta(pL.elimina());
                        }
                        if(pL.getTope()==null){
                            JOptionPane.showMessageDialog(null, "No existe un correo con ese número");
                        }else{
                            pS.inserta(pL.elimina());
                        }
                        Nodo de = aux.getTope();
                        while(de!=null){
                            pL.inserta(aux.elimina());
                            de=aux.getTope();
                        }
                        mostrarEliminados();
                    }
                }
            }
            if (ventana==4) {
                JOptionPane.showMessageDialog(null, "No se puede enviar a spam un correo que ya fue enviado a spam");
            }
        }
        txtSpam.setText("");
        FileOutputStream fo=null;
            try {
                fo = new FileOutputStream(path);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Visualizar.class.getName()).log(Level.SEVERE, null, ex);
            }
            ObjectOutputStream oo=null;
            try {
                oo = new ObjectOutputStream(fo);
            } catch (IOException ex) {
                Logger.getLogger(Visualizar.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                oo.writeObject(r);
            } catch (IOException ex) {
                Logger.getLogger(Visualizar.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                oo.close();
            } catch (IOException ex) {
                Logger.getLogger(Visualizar.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                fo.close();
            } catch (IOException ex) {
                Logger.getLogger(Visualizar.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_EspamActionPerformed

    private void CancelarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarRActionPerformed
        PanelRe.setVisible(false);
        PanelE.setVisible(false);
    }//GEN-LAST:event_CancelarRActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        PanelRe.setVisible(false);
        PanelE.setVisible(false);
    }//GEN-LAST:event_CancelarActionPerformed

    private void DestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DestinoActionPerformed

    private void RecibirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecibirActionPerformed
        if (OrigenR.getText().equals("") || MensajeR.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "No deje ningún espacio vacio");
        } 
        else if (mesr.getSelectedItem().equals("02") && Integer.parseInt((String) diar.getSelectedItem())>28){
            JOptionPane.showMessageDialog(null, "Fecha invalida.\nRecuerde que no todos los meses tienen el mismo número de días.");
        }
        else if ((mesr.getSelectedItem().equals("04")||mesr.getSelectedItem().equals("06")||mesr.getSelectedItem().equals("09")||mesr.getSelectedItem().equals("11")) && Integer.parseInt((String) diar.getSelectedItem())>30){
            JOptionPane.showMessageDialog(null, "Fecha invalida.\nRecuerde que no todos los meses tienen el mismo número de días.");
        }
        else {
            String dia = (String) diar.getSelectedItem();
            String mes = (String) mesr.getSelectedItem();
            String year = (String) yearr.getSelectedItem();
            String FechaR = dia+"/"+mes+"/"+year.substring(2,4);
            Nodo <String> n = new Nodo <String> (FechaR+" | "+OrigenR.getText()+" | "+MensajeR.getText());
            pB.inserta(n);
            mostrarBandeja();
            OrigenR.setText("");
            MensajeR.setText("");
            PanelRe.setVisible(false);
            PanelE.setVisible(false);
        }
        FileOutputStream fo=null;
            try {
                fo = new FileOutputStream(path);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Visualizar.class.getName()).log(Level.SEVERE, null, ex);
            }
            ObjectOutputStream oo=null;
            try {
                oo = new ObjectOutputStream(fo);
            } catch (IOException ex) {
                Logger.getLogger(Visualizar.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                oo.writeObject(r);
            } catch (IOException ex) {
                Logger.getLogger(Visualizar.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                oo.close();
            } catch (IOException ex) {
                Logger.getLogger(Visualizar.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                fo.close();
            } catch (IOException ex) {
                Logger.getLogger(Visualizar.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_RecibirActionPerformed

    private void BandejaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BandejaActionPerformed
        ventana=1;
        mostrarBandeja();
    }//GEN-LAST:event_BandejaActionPerformed

    private void Enviar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Enviar2ActionPerformed
        if (Destino2.getText().equals("") || Mensaje2.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "No deje ningún espacio vacio");
        }
        else if (mesr1.getSelectedItem().equals("02") && Integer.parseInt((String) diar1.getSelectedItem())>28){
            JOptionPane.showMessageDialog(null, "Fecha invalida.\nRecuerde que no todos los meses tienen el mismo número de días.");
        }
        else if ((mesr1.getSelectedItem().equals("04")||mesr1.getSelectedItem().equals("06")||mesr1.getSelectedItem().equals("09")||mesr1.getSelectedItem().equals("11")) && Integer.parseInt((String) diar1.getSelectedItem())>30){
            JOptionPane.showMessageDialog(null, "Fecha invalida.\nRecuerde que no todos los meses tienen el mismo número de días.");
        }
        else {
            String dia = (String) diar1.getSelectedItem();
            String mes = (String) mesr1.getSelectedItem();
            String year = (String) yearr1.getSelectedItem();
            String Fecha2 = dia+"/"+mes+"/"+year.substring(2,4);
            Nodo <String> n = new Nodo <String> (Fecha2+" | "+Destino2.getText()+" | "+Mensaje2.getText());
            pE.inserta(n);
            mostrarEnviados();
            Destino2.setText("");
            Mensaje2.setText("");
            PanelRe.setVisible(false);
            PanelE.setVisible(false);
        }
        FileOutputStream fo=null;
            try {
                fo = new FileOutputStream(path);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Visualizar.class.getName()).log(Level.SEVERE, null, ex);
            }
            ObjectOutputStream oo=null;
            try {
                oo = new ObjectOutputStream(fo);
            } catch (IOException ex) {
                Logger.getLogger(Visualizar.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                oo.writeObject(r);
            } catch (IOException ex) {
                Logger.getLogger(Visualizar.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                oo.close();
            } catch (IOException ex) {
                Logger.getLogger(Visualizar.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                fo.close();
            } catch (IOException ex) {
                Logger.getLogger(Visualizar.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_Enviar2ActionPerformed

    private void EnviadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviadosActionPerformed
        ventana=2;
        mostrarEnviados();
    }//GEN-LAST:event_EnviadosActionPerformed

    private void EliminadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminadosActionPerformed
        ventana=3;
        mostrarEliminados();
    }//GEN-LAST:event_EliminadosActionPerformed

    private void SpamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpamActionPerformed
        ventana=4;
        mostrarSpam();
    }//GEN-LAST:event_SpamActionPerformed

    private void QuienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuienActionPerformed
        JOptionPane.showMessageDialog(null, "Mi correo: "+correo+"\nMi nombre: "+nombre+"\nMi edad: "+edad);
    }//GEN-LAST:event_QuienActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        if (txtBuscar.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese el correo que desea buscar");
        } else {
            int t = txtBuscar.getText().length();
            String tx = "";
            String con="";
            String v[]= new String[20];
            int i=0;
            if (ventana==1) {
                Nodo de = pB.getTope();
                while(de!=null){
                    tx = (String) de.getObj();
                    if (txtBuscar.getText().toUpperCase().equals(tx.substring(11, 11+t).toUpperCase())) {
                        //aux.inserta(de);
                        con=de.getObj()+"\n";
                        con=con+"____________________________________________________________"+"\n";
                        v[i]=con;
                        i++;
                    }
                    de=de.getSig();
                }
                con="";
                for (int s = 0; s < 20; s++) {
                    if (v[s]!=null) {
                       con=con+v[s]; 
                    }
                }
                vista.setText(con);
                txtBuscar.setText("");
            }
            if (ventana==2) {
                Nodo de = pE.getTope();
                while(de!=null){
                    tx = (String) de.getObj();
                    if (txtBuscar.getText().toUpperCase().equals(tx.substring(11, 11+t).toUpperCase())) {
                        //aux.inserta(de);
                        con=de.getObj()+"\n";
                        con=con+"____________________________________________________________"+"\n";
                        v[i]=con;
                        i++;
                    }
                    de=de.getSig();
                }
                con="";
                for (int s = 0; s < 20; s++) {
                    if (v[s]!=null) {
                       con=con+v[s]; 
                    }
                }
                vista.setText(con);
                txtBuscar.setText("");
            }
            if (ventana==3) {
                Nodo de = pL.getTope();
                while(de!=null){
                    tx = (String) de.getObj();
                    if (txtBuscar.getText().toUpperCase().equals(tx.substring(11, 11+t).toUpperCase())) {
                        //aux.inserta(de);
                        con=de.getObj()+"\n";
                        con=con+"____________________________________________________________"+"\n";
                        v[i]=con;
                        i++;
                    }
                    de=de.getSig();
                }
                con="";
                for (int s = 0; s < 20; s++) {
                    if (v[s]!=null) {
                       con=con+v[s]; 
                    }
                }
                vista.setText(con);
                txtBuscar.setText("");
            }
            if (ventana==4) {
                Nodo de = pS.getTope();
                while(de!=null){
                    tx = (String) de.getObj();
                    if (txtBuscar.getText().toUpperCase().equals(tx.substring(11, 11+t).toUpperCase())) {
                        //aux.inserta(de);
                        con=de.getObj()+"\n";
                        con=con+"____________________________________________________________"+"\n";
                        v[i]=con;
                        i++;
                    }
                    de=de.getSig();
                }
                con="";
                for (int s = 0; s < 20; s++) {
                    if (v[s]!=null) {
                       con=con+v[s]; 
                    }
                }
                vista.setText(con);
                txtBuscar.setText("");
            }
        }
    }//GEN-LAST:event_BuscarActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        this.setVisible(false);
        try {
            Menu men = new Menu();
            men.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Visualizar.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Visualizar.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_salirActionPerformed

    private void cambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarActionPerformed
        String per = (String)JOptionPane.showInputDialog(null, "Elija de quien es el correo al que desea ingresar inicialmente:", "Ver bandeja", JOptionPane.QUESTION_MESSAGE, null, obtenerOpcPer(), obtenerOpcPer()[0]);
        if(per!=null){
            Nodo t = ml.busca(r, per);
            if(t.getAbj()!=null){
                String ma = (String)JOptionPane.showInputDialog(null, "Elija el correo al que desea ingresar:", "Ver bandeja", JOptionPane.QUESTION_MESSAGE, null, obtenerOpcCor(per), obtenerOpcCor(per)[0]);
                if(ma!=null){

                    t = t.getAbj();
                    Nodo b = ml.busca(t, ma);
                    b=b.getAbj();
                    Visualizar v = new Visualizar(per,b.getD(), b.edad, r, ml, b.pB, b.pE, b.pL, b.pS);
                    this.setVisible(false);
                    v.setVisible(true);
                }else{
                    System.out.println("accion cancelada");
                }
            }else{
            JOptionPane.showMessageDialog(null, "La persona seleccionada no tiene asociado ningún correo");
            }
        }else{
            System.out.println("accion cancelada");
        }
    }//GEN-LAST:event_cambiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public String[] obtenerOpcPer(){
        int c=0;
        Nodo t=r;
        while (t != null)
        {
            c++;
            t = t.getSig();
        }
        String v[] = new String [c];
        t=r;
        int i=0;
        while (t != null)
        {
            v[i]=t.getD();
            t = t.getSig();
            i++;
        }
        return v;
    }
    public String[] obtenerOpcCor(String per){
        Nodo pr = ml.busca(r, per);
        int c=0;
        Nodo t=pr.getAbj();
        while (t != null)
        {
            c++;
            t = t.getSig();
        }
        String v[] = new String [c];
        t=pr.getAbj();
        int i=0;
        while (t != null)
        {
            v[i]=t.getD();
            t = t.getSig();
            i++;
        }
        return v;
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Visualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Visualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Visualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Visualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Visualizar().setVisible(true);
            }
        });
    }
    public static void mostrarBandeja(){
        if(pB!=null){
            String texto="";
            Nodo de=pB.getTope();
            while(de!=null){
                texto=texto+de.getObj()+"\n";
                texto=texto+"____________________________________________________________"+"\n";
                de=de.getSig();
            }
            vista.setText(texto);
        }else{
            vista.setText("");
        }
        
    } 
    public static void mostrarEnviados(){
        String texto="";
        Nodo de=pE.getTope();
        while(de!=null){
            texto=texto+de.getObj()+"\n";
            texto=texto+"____________________________________________________________"+"\n";
            de=de.getSig();
        }
        vista.setText(texto);
        
    } 
    public static void mostrarEliminados(){
        String texto="";
        Nodo de=pL.getTope();
        while(de!=null){
            texto=texto+de.getObj()+"\n";
            texto=texto+"____________________________________________________________"+"\n";
            de=de.getSig();
        }
        vista.setText(texto);
        
    } 
    public static void mostrarSpam(){
        String texto="";
        Nodo de=pS.getTope();
        while(de!=null){
            texto=texto+de.getObj()+"\n";
            texto=texto+"____________________________________________________________"+"\n";
            de=de.getSig();
        }
        vista.setText(texto);
        
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bandeja;
    private javax.swing.JButton Buscar;
    private javax.swing.JButton Cancelar2;
    private javax.swing.JButton CancelarR;
    private javax.swing.JTextField Destino2;
    private javax.swing.JLabel DestinoR;
    private javax.swing.JButton Eliminados;
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton Enviados;
    private javax.swing.JButton Enviar2;
    private javax.swing.JButton Espam;
    private javax.swing.JTextArea Mensaje2;
    private javax.swing.JTextArea MensajeR;
    private javax.swing.JButton MostrarE;
    private javax.swing.JLabel Origen2;
    private javax.swing.JTextField OrigenR;
    private javax.swing.JPanel PanelE;
    private javax.swing.JPanel PanelRe;
    private javax.swing.JButton Quien;
    private javax.swing.JButton Recibir;
    private javax.swing.JButton Spam;
    private javax.swing.JButton cambiar;
    private javax.swing.JComboBox<String> diar;
    private javax.swing.JComboBox<String> diar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JComboBox<String> mesr;
    private javax.swing.JComboBox<String> mesr1;
    private javax.swing.JButton salir;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtEliminar;
    private javax.swing.JTextField txtSpam;
    private static javax.swing.JTextArea vista;
    private javax.swing.JComboBox<String> yearr;
    private javax.swing.JComboBox<String> yearr1;
    // End of variables declaration//GEN-END:variables
}
